### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by moritz2212** [jk/php-wsdl-creator#1]
How can I integrate this into an existing Framework, or execute authentication via existing Framework with this tool?

**Comment by jk** [comment]
You're in the wrong place.

1. This repo is a mirror of https://code.google.com/archive/p/php-wsdl-creator/ (you could have find that info in the README)
2. Your question is too broad.
3. Your question isn't targeted to what the php-wsdl-creator tries to do for you - so you'll probably even won't get an answer from the original author. You probably should ask your questions on something like StackOverflow or a forum/community for your specific framework.
